"""followers

Revision ID: 79087d72b1f8
Revises: 94fe709dca3d
Create Date: 2021-09-23 18:13:26.448252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79087d72b1f8'
down_revision = '94fe709dca3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
