"""empty message

Revision ID: e1e1669eeff0
Revises: bc0d0e0365b1
Create Date: 2021-10-01 18:12:51.268250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e1669eeff0'
down_revision = 'bc0d0e0365b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobpost', sa.Column('date_posted', sa.DateTime(), nullable=True))
    op.alter_column('jobpost', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_jobpost_dateposted', table_name='jobpost')
    op.create_index(op.f('ix_jobpost_date_posted'), 'jobpost', ['date_posted'], unique=False)
    op.drop_column('jobpost', 'dateposted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobpost', sa.Column('dateposted', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_jobpost_date_posted'), table_name='jobpost')
    op.create_index('ix_jobpost_dateposted', 'jobpost', ['dateposted'], unique=False)
    op.alter_column('jobpost', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('jobpost', 'date_posted')
    # ### end Alembic commands ###
